# Generated by Django 3.1.2 on 2023-06-30 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image_file',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='service_headers'),
        ),
    ]
