# Generated by Django 3.1.2 on 2023-10-19 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_service_image_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='image_file',
        ),
    ]
