# Generated by Django 3.1.2 on 2024-09-23 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20240325_0016'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HowToFeel',
        ),
    ]
