# Generated by Django 3.1.2 on 2024-09-23 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_delete_howtofeel'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='img_alt_text',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='service',
            name='image_file',
            field=models.ImageField(blank=True, default='', upload_to='services'),
        ),
    ]
