# Generated by Django 3.1.2 on 2024-09-23 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20240923_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image_file',
            field=models.ImageField(blank=True, upload_to='services'),
        ),
        migrations.AlterField(
            model_name='service',
            name='img_alt_text',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
