# Generated by Django 3.1.2 on 2025-01-23 15:36

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20240923_2326'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(upload_to='post_headers')),
                ('title', models.CharField(max_length=250)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(max_length=14000)),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField(editable=False)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('meta_title', models.CharField(blank=True, default='', max_length=250)),
                ('meta_description', models.TextField(blank=True, default='')),
                ('meta_keywords', models.CharField(blank=True, default='', max_length=500)),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
