# Generated by Django 3.1.2 on 2025-01-25 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_carrer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carrer',
            options={'verbose_name': 'Carrer', 'verbose_name_plural': 'Carrers'},
        ),
    ]
