# Generated by Django 3.1.2 on 2025-01-29 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20250125_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='howtofeel',
            name='image_file',
            field=models.ImageField(blank=True, upload_to='careers'),
        ),
    ]
