# Generated by Django 3.1.2 on 2025-01-30 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20250129_2156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='howtofeel',
            options={'verbose_name': 'Career', 'verbose_name_plural': 'Jds'},
        ),
    ]
