# Generated by Django 3.1.2 on 2025-01-30 16:30

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20250130_2149'),
    ]

    operations = [
        migrations.CreateModel(
            name='HowToFeel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(blank=True, upload_to='careers')),
                ('title', models.CharField(max_length=250)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(max_length=14000)),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('meta_title', models.CharField(blank=True, default='', max_length=250)),
                ('meta_description', models.TextField(blank=True, default='')),
                ('meta_keywords', models.CharField(blank=True, default='', max_length=500)),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
        migrations.DeleteModel(
            name='Jd',
        ),
    ]
